=== DaoNgocTien/XmlFoodRecommendation/SE1302_Meal_Webservice/build/web/WEB-INF/material.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           xmlns="http://xml.netbeans.org/schema/materials"
           targetNamespace="http://xml.netbeans.org/schema/materials">
    <xs:complexType name="attributes">
        <xs:sequence>
            <xs:element name="foodname">
                <xs:simpleType>
                    <xs:restriction  base="xs:string">
                        <xs:minLength value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="carbonhydrate">
                <xs:simpleType>
                    <xs:restriction  base="xs:decimal">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="fiber">
                <xs:simpleType>
                    <xs:restriction  base="xs:decimal">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="fat">
                <xs:simpleType>
                    <xs:restriction  base="xs:decimal">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="protein">
                <xs:simpleType>
                    <xs:restriction  base="xs:decimal">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="calories">
                <xs:simpleType>
                    <xs:restriction  base="xs:decimal">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="materials">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="material" type="attributes" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DaoNgocTien/XmlFoodRecommendation/SE1302_Meal_Webservice/build/web/WEB-INF/validatedXML.xml
<?xml version="1.0" encoding="UTF-8"?><materials xsi:schemaLocation="http://xml.netbeans.org/schema/materials material.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://xml.netbeans.org/schema/materials">
<material>
<foodname>Bánh mì đen</foodname>
<carbonhydrate>48</carbonhydrate>
<fiber>7</fiber>
<fat>3</fat>
<protein>9</protein>
<calories>250</calories>
</material>
<material>
<foodname>Bánh mì</foodname>
<carbonhydrate>48</carbonhydrate>
<fiber>4</fiber>
<fat>4</fat>
<protein>1</protein>
<calories>266</calories>
</material>
<material>
<foodname>Bí xanh (baby)</foodname>
<carbonhydrate>3</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>3</protein>
<calories>21</calories>
</material>
<material>
<foodname>Bí xanh (mùa hè)</foodname>
<carbonhydrate>3</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>16</calories>
</material>
<material>
<foodname>Bí đao</foodname>
<carbonhydrate>3</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>0</protein>
<calories>14</calories>
</material>
<material>
<foodname>Bông hẹ</foodname>
<carbonhydrate>4</carbonhydrate>
<fiber>3</fiber>
<fat>1</fat>
<protein>3</protein>
<calories>30</calories>
</material>
<material>
<foodname>Bưởi chùm</foodname>
<carbonhydrate>8</carbonhydrate>
<fiber>1.3</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>33</calories>
</material>
<material>
<foodname>Bưởi</foodname>
<carbonhydrate>10</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>38</calories>
</material>
<material>
<foodname>Bầu</foodname>
<carbonhydrate>4</carbonhydrate>
<fiber>0</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>20</calories>
</material>
<material>
<foodname>Bắp ngô ngọt</foodname>
<carbonhydrate>19</carbonhydrate>
<fiber>3</fiber>
<fat>1</fat>
<protein>3</protein>
<calories>86</calories>
</material>
<material>
<foodname>Cam (quả)</foodname>
<carbonhydrate>12</carbonhydrate>
<fiber>2</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>47</calories>
</material>
<material>
<foodname>Chanh (quả)</foodname>
<carbonhydrate>11</carbonhydrate>
<fiber>3</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>30</calories>
</material>
<material>
<foodname>Chanh dây</foodname>
<carbonhydrate>23</carbonhydrate>
<fiber>10</fiber>
<fat>1</fat>
<protein>2</protein>
<calories>97</calories>
</material>
<material>
<foodname>Chuối</foodname>
<carbonhydrate>23</carbonhydrate>
<fiber>3</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>89</calories>
</material>
<material>
<foodname>Chôm chôm</foodname>
<carbonhydrate>21</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>82</calories>
</material>
<material>
<foodname>Cà chua vàng / cam</foodname>
<carbonhydrate>3</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>15</calories>
</material>
<material>
<foodname>Cà chua xanh</foodname>
<carbonhydrate>5</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>23</calories>
</material>
<material>
<foodname>Cà rốt</foodname>
<carbonhydrate>10</carbonhydrate>
<fiber>3</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>41</calories>
</material>
<material>
<foodname>Cà tím</foodname>
<carbonhydrate>6</carbonhydrate>
<fiber>3</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>24</calories>
</material>
<material>
<foodname>Cây atisô</foodname>
<carbonhydrate>11</carbonhydrate>
<fiber>5</fiber>
<fat>0</fat>
<protein>3</protein>
<calories>47</calories>
</material>
<material>
<foodname>Cây bạc hà cay</foodname>
<carbonhydrate>15</carbonhydrate>
<fiber>8</fiber>
<fat>1</fat>
<protein>4</protein>
<calories>70</calories>
</material>
<material>
<foodname>Cây bạc hà lục</foodname>
<carbonhydrate>8</carbonhydrate>
<fiber>7</fiber>
<fat>1</fat>
<protein>3</protein>
<calories>44</calories>
</material>
<material>
<foodname>Cây đại hoàng</foodname>
<carbonhydrate>5</carbonhydrate>
<fiber>1.5</fiber>
<fat>0</fat>
<protein>0.8</protein>
<calories>21</calories>
</material>
<material>
<foodname>Cải bắp</foodname>
<carbonhydrate>6</carbonhydrate>
<fiber>3</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>25</calories>
</material>
<material>
<foodname>Cải cúc / rau tần ô</foodname>
<carbonhydrate>3</carbonhydrate>
<fiber>3</fiber>
<fat>1</fat>
<protein>3</protein>
<calories>24</calories>
</material>
<material>
<foodname>Cải ngồng/cải rổ</foodname>
<carbonhydrate>4</carbonhydrate>
<fiber>3</fiber>
<fat>1</fat>
<protein>1</protein>
<calories>22</calories>
</material>
<material>
<foodname>Cải thìa</foodname>
<carbonhydrate>2</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>9</calories>
</material>
<material>
<foodname>Cải thảo</foodname>
<carbonhydrate>3</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>16</calories>
</material>
<material>
<foodname>Cải xanh turnips</foodname>
<carbonhydrate>7</carbonhydrate>
<fiber>3</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>32</calories>
</material>
<material>
<foodname>Cải xoong / xà lách xoong</foodname>
<carbonhydrate>1</carbonhydrate>
<fiber>0</fiber>
<fat>0</fat>
<protein>2</protein>
<calories>11</calories>
</material>
<material>
<foodname>Cải xoăn Kale</foodname>
<carbonhydrate>10.5</carbonhydrate>
<fiber>1.5</fiber>
<fat>0</fat>
<protein>3</protein>
<calories>49</calories>
</material>
<material>
<foodname>Cần tây</foodname>
<carbonhydrate>4</carbonhydrate>
<fiber>2</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>16</calories>
</material>
<material>
<foodname>Củ cái trắng</foodname>
<carbonhydrate>3</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>14</calories>
</material>
<material>
<foodname>Củ diếp xoắn</foodname>
<carbonhydrate>18</carbonhydrate>
<fiber>0</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>73</calories>
</material>
<material>
<foodname>Củ dền</foodname>
<carbonhydrate>10</carbonhydrate>
<fiber>3</fiber>
<fat>0</fat>
<protein>2</protein>
<calories>43</calories>
</material>
<material>
<foodname>Củ hành</foodname>
<carbonhydrate>9</carbonhydrate>
<fiber>2</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>40</calories>
</material>
<material>
<foodname>Củ nghệ (gia vị)</foodname>
<carbonhydrate>65</carbonhydrate>
<fiber>21</fiber>
<fat>10</fat>
<protein>8</protein>
<calories>354</calories>
</material>
<material>
<foodname>Củ từ</foodname>
<carbonhydrate>28</carbonhydrate>
<fiber>4</fiber>
<fat>0</fat>
<protein>2</protein>
<calories>118</calories>
</material>
<material>
<foodname>Củ đậu</foodname>
<carbonhydrate>9</carbonhydrate>
<fiber>5</fiber>
<fat>0</fat>
<protein>0.8</protein>
<calories>38</calories>
</material>
<material>
<foodname>Diếp Lô Lô</foodname>
<carbonhydrate>3</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1.5</protein>
<calories>12</calories>
</material>
<material>
<foodname>Dâu tây</foodname>
<carbonhydrate>8</carbonhydrate>
<fiber>2</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>32</calories>
</material>
<material>
<foodname>Dưa chuột có vỏ</foodname>
<carbonhydrate>4</carbonhydrate>
<fiber>0</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>15</calories>
</material>
<material>
<foodname>Dưa chuột gọt vỏ</foodname>
<carbonhydrate>2</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>12</calories>
</material>
<material>
<foodname>Dưa cải bắp</foodname>
<carbonhydrate>5</carbonhydrate>
<fiber>1.5</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>25</calories>
</material>
<material>
<foodname>Dưa cải bẹ</foodname>
<carbonhydrate>4.5</carbonhydrate>
<fiber>2</fiber>
<fat>0</fat>
<protein>2</protein>
<calories>17</calories>
</material>
<material>
<foodname>Dưa gang</foodname>
<carbonhydrate>7</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>28</calories>
</material>
<material>
<foodname>Dưa hấu</foodname>
<carbonhydrate>8</carbonhydrate>
<fiber>0</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>30</calories>
</material>
<material>
<foodname>Dưa lưới (honeydew), dưa lê</foodname>
<carbonhydrate>9</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>36</calories>
</material>
<material>
<foodname>Dưa ruột vàng (cantaloupe)</foodname>
<carbonhydrate>9</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>34</calories>
</material>
<material>
<foodname>Dưa vàng (casaba)</foodname>
<carbonhydrate>7</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>28</calories>
</material>
<material>
<foodname>Dọc mùng</foodname>
<carbonhydrate>3.8</carbonhydrate>
<fiber>0.5</fiber>
<fat>0</fat>
<protein>0.25</protein>
<calories>14</calories>
</material>
<material>
<foodname>Dứa</foodname>
<carbonhydrate>13</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>50</calories>
</material>
<material>
<foodname>Dừa, cùi</foodname>
<carbonhydrate>15</carbonhydrate>
<fiber>9</fiber>
<fat>33</fat>
<protein>3</protein>
<calories>354</calories>
</material>
<material>
<foodname>Dừa, nước</foodname>
<carbonhydrate>4</carbonhydrate>
<fiber>1</fiber>
<fat>0</fat>
<protein>1</protein>
<calories>19</calories>
</material>
<material>
<foodname>Giá đỗ</foodname>
<carbonhydrate>7.5</carbonhydrate>
<fiber>2</fiber>
<fat>0</fat>
<protein>5.5</protein>
<calories>44</calories>
</material>
<material>
<foodname>Gạo nâu / gạo lức</foodname>
<carbonhydrate>77</carbonhydrate>
<fiber>4</fiber>
<fat>3</fat>
<protein>8</protein>
<calories>370</calories>
</material>
<material>
<foodname>Gạo nếp</foodname>
<carbonhydrate>82</carbonhydrate>
<fiber>3</fiber>
<fat>1</fat>
<protein>7</protein>
<calories>370</calories>
</material>
<material>
<foodname>Gạo trắng</foodname>
<carbonhydrate>79</carbonhydrate>
<fiber>3</fiber>
<fat>1</fat>
<protein>6</protein>
<calories>360</calories>
</material>
<material>
<foodname>Gừng</foodname>
<carbonhydrate>18</carbonhydrate>
<fiber>2</fiber>
<fat>1</fat>
<protein>2</protein>
<calories>80</calories>
</material>
<material>
<foodname>Hoa chuối</foodname>
